version: '2'
services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=Password
    expose:
      - 3306
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
  flask:
    build: .
    restart: always
    ports:
            - 5000:5000
    volumes:
      - ./app:/app:ro