version: '3'

services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=microblog
      - MYSQL_PASSWORD=microblog
      - MYSQL_USER=microblog
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  flask:
    build: .
    container_name: planner
    restart: always
    environment:
        - DATABASE_URL=mysql+pymysql://microblog:microblog@mysql/microblog
    volumes:
      - ./app:/app:ro
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
