version: '3'

services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=microblog
      - MYSQL_PASSWORD=microblog
      - MYSQL_USER=microblog
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  flask:
    build: .
    container_name: planner
    restart: always
    environment:
        - DATABASE_URL=mysql+pymysql://microblog:microblog@mysql/microblog
    volumes:
      - ./app:/app:ro
    depends_on:
      - mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80  # Map port 8080 of the host to port 80 of the container (default for phpMyAdmin)
    environment:
      PMA_HOST: mysql  # Set the database host to the 'mysql' service name
      PMA_USER: microblog  # Set the database username (replace if different)
      PMA_PASSWORD: microblog  # Set the database password (replace if different)
    networks:
      - app-network


networks:
  app-network:
