"""empty message

Revision ID: 368856be5a67
Revises: a8262f5edfdf
Create Date: 2024-01-04 14:09:44.008157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368856be5a67'
down_revision = 'a8262f5edfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_creator_username', type_='foreignkey')
        batch_op.drop_column('creator_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_username', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_foreign_key('fk_todo_creator_username', 'user', ['creator_username'], ['username'])

    # ### end Alembic commands ###
